import { Platform, StyleSheet } from 'react-native';

const isWeb = Platform.OS === 'web';
const webDesktopShellMaxWidth = 1180;

export const styles = StyleSheet.create({
  loginScreen: {
    flex: 1,
    backgroundColor: '#0B1020',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  loginCard: {
    alignSelf: 'center',
    backgroundColor: '#151A2D',
    borderColor: '#2C3560',
    borderRadius: 28,
    borderWidth: 1,
    maxWidth: isWeb ? 680 : undefined,
    padding: 22,
    gap: 10,
    width: '100%',
  },
  loginTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  demoChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#252B49',
    marginBottom: 4,
  },
  input: {
    backgroundColor: '#171A2A',
  },
  helperText: {
    color: '#95A0C8',
  },
  successText: {
    color: '#7DFFB3',
  },
  loginButton: {
    marginTop: 6,
  },
  screen: {
    flex: 1,
    backgroundColor: '#0B1020',
  },
  content: {
    paddingHorizontal: isWeb ? 24 : 18,
    paddingTop: isWeb ? 40 : 64,
    paddingBottom: 120,
  },
  contentShell: {
    width: '100%',
    alignSelf: 'center',
    maxWidth: isWeb ? webDesktopShellMaxWidth : undefined,
    gap: 16,
  },
  sectionStack: {
    gap: 16,
  },
  desktopSplitLayout: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 16,
  },
  desktopMainColumn: {
    flex: 1,
    minWidth: 0,
    gap: 16,
  },
  desktopSideColumn: {
    flexBasis: 420,
    flexGrow: 1,
    minWidth: 320,
    maxWidth: 440,
    gap: 16,
  },
  desktopBalancedColumn: {
    flex: 1,
    minWidth: 320,
    gap: 16,
  },
  desktopPanelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 16,
  },
  desktopPanelTile: {
    flexGrow: 1,
    flexBasis: 340,
    minWidth: 320,
  },
  desktopFullSpan: {
    width: '100%',
    flexBasis: '100%',
  },
  desktopHeroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: 16,
  },
  desktopHeroPane: {
    flex: 1.35,
    minWidth: 420,
    alignSelf: 'stretch',
  },
  desktopStatsPane: {
    flex: 1,
    minWidth: 300,
    gap: 12,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  desktopStatsStack: {
    flexDirection: 'column',
    flexWrap: 'nowrap',
  },
  desktopCardStretch: {
    alignSelf: 'stretch',
  },
  desktopFriendsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 16,
    justifyContent: 'center',
  },
  desktopFriendTile: {
    flexGrow: 1,
    flexBasis: 340,
    minWidth: 320,
    maxWidth: 420,
  },
  eyebrow: {
    color: '#7DFFB3',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  pageTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  pageSubtitle: {
    color: '#A7B0D6',
    fontSize: 15,
    lineHeight: 22,
  },
  pageHeaderBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  pageHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  accountAvatarTrigger: {
    alignSelf: 'flex-start',
    backgroundColor: '#171D33',
    borderColor: '#2C3560',
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 2,
    padding: 4,
  },
  accountAvatarTriggerActive: {
    backgroundColor: '#2B3151',
    borderColor: '#7C5CFF',
  },
  accountAvatarTriggerHovered: {
    transform: [{ scale: 1.06 }],
  },
  accountAvatarFrame: {
    borderRadius: 999,
    overflow: 'hidden',
  },
  accountAvatarImage: {
    backgroundColor: '#6F63A8',
  },
  accountAvatarFallbackLabel: {
    color: '#F5F7FF',
    fontWeight: '700',
  },
  accountMenuContent: {
    backgroundColor: '#141A2D',
    borderColor: '#2C3560',
    borderRadius: 18,
    borderWidth: 1,
    minWidth: 220,
    paddingVertical: 8,
  },
  accountMenuList: {
    gap: 4,
  },
  accountMenuIdentity: {
    gap: 4,
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 8,
  },
  accountMenuIdentityName: {
    color: '#F5F7FF',
    fontWeight: '700',
  },
  accountMenuIdentityHandle: {
    color: '#95A0C8',
    fontSize: 13,
  },
  accountMenuDivider: {
    backgroundColor: '#2C3560',
    marginHorizontal: 8,
    marginBottom: 4,
  },
  accountMenuAction: {
    alignSelf: 'stretch',
    borderRadius: 12,
    marginHorizontal: 8,
  },
  accountMenuActionContent: {
    justifyContent: 'flex-start',
    minHeight: 40,
  },
  accountMenuActionLabel: {
    color: '#F5F7FF',
    fontWeight: '600',
  },
  segmented: {
    marginTop: 4,
  },
  desktopSectionNavShell: {
    marginTop: 4,
    backgroundColor: '#141A2D',
    borderColor: '#2C3560',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    overflow: 'hidden',
  },
  desktopSectionNavPressable: {
    flex: 1,
    minWidth: 0,
  },
  desktopSectionNavPressablePressed: {
    opacity: 0.92,
  },
  desktopSectionNavButton: {
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  desktopSectionNavButtonWithDivider: {
    borderRightColor: '#2C3560',
    borderRightWidth: 1,
  },
  desktopSectionNavButtonActive: {
    backgroundColor: '#4C4559',
  },
  desktopSectionNavButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  desktopSectionNavButtonLabel: {
    color: '#F5F7FF',
    fontWeight: '600',
  },
  desktopSectionNavButtonLabelActive: {
    fontWeight: '700',
  },
  desktopSectionNavButtonBadge: {
    backgroundColor: '#FF6B81',
  },
  desktopSectionNavButtonBadgeActive: {
    backgroundColor: '#F58CA0',
  },
  mobileSectionNavShell: {
    marginTop: 4,
    backgroundColor: '#141A2D',
    borderColor: '#2C3560',
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mobileSectionNavSummary: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  mobileSectionNavEyebrow: {
    color: '#95A0C8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  mobileSectionNavCurrent: {
    color: '#F5F7FF',
    fontWeight: '700',
  },
  mobileSectionNavButtonWrap: {
    position: 'relative',
  },
  mobileSectionNavMenuButton: {
    margin: 0,
  },
  mobileSectionNavBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#FF6B81',
  },
  mobileSectionMenuContent: {
    backgroundColor: '#141A2D',
    borderColor: '#2C3560',
    borderRadius: 18,
    borderWidth: 1,
    minWidth: 220,
    paddingVertical: 8,
  },
  mobileSectionMenuList: {
    gap: 4,
  },
  mobileSectionMenuAccount: {
    backgroundColor: '#1A2037',
    borderRadius: 14,
    gap: 6,
    marginHorizontal: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  mobileSectionMenuAccountEyebrow: {
    color: '#95A0C8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  mobileSectionMenuAccountName: {
    color: '#F5F7FF',
    fontWeight: '700',
  },
  mobileSectionMenuAccountLogout: {
    alignSelf: 'flex-start',
    marginLeft: -8,
  },
  mobileSectionMenuDivider: {
    backgroundColor: '#2C3560',
    marginHorizontal: 8,
    marginVertical: 4,
  },
  mobileSectionMenuButton: {
    alignSelf: 'stretch',
    borderRadius: 12,
    marginHorizontal: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  mobileSectionMenuButtonActive: {
    backgroundColor: '#4C4559',
  },
  mobileSectionMenuButtonPressed: {
    opacity: 0.92,
  },
  mobileSectionMenuButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-start',
    minHeight: 24,
  },
  mobileSectionMenuButtonLabelRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  mobileSectionMenuButtonLabel: {
    color: '#F5F7FF',
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'left',
  },
  mobileSectionMenuButtonBadge: {
    backgroundColor: '#FF6B81',
  },
  mobileSectionMenuButtonCheck: {
    color: '#F5F7FF',
    fontSize: 18,
    fontWeight: '700',
  },
  heroCard: {
    backgroundColor: '#161B31',
    borderColor: '#2C3560',
    borderRadius: 28,
    borderWidth: 1,
    width: isWeb ? '100%' : undefined,
    padding: 20,
    gap: 14,
  },
  liveChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#252B49',
  },
  heroTitle: {
    color: '#F7F8FF',
    fontWeight: '800',
  },
  heroCopy: {
    color: '#B9C0E0',
    fontSize: 15,
    lineHeight: 22,
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  dashboardAgendaCard: {
    maxWidth: undefined,
    alignSelf: 'stretch',
  },
  dashboardAgendaHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    justifyContent: 'space-between',
  },
  dashboardAgendaHeaderCopy: {
    flex: 1,
    gap: 10,
    minWidth: isWeb ? 320 : 0,
  },
  dashboardAgendaGroups: {
    gap: 14,
    marginTop: 6,
    width: '100%',
  },
  dashboardAgendaDayGroup: {
    gap: 8,
  },
  dashboardAgendaDayLabel: {
    color: '#DDE4FF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  dashboardAgendaDayItems: {
    gap: 10,
  },
  dashboardAgendaEventCard: {
    backgroundColor: '#11172B',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  dashboardAgendaEventHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  dashboardAgendaEventMeta: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  dashboardAgendaEventTime: {
    color: '#D8DDF4',
    fontSize: 14,
    fontWeight: '700',
  },
  dashboardAgendaEmptyCard: {
    alignSelf: 'stretch',
    backgroundColor: '#11172B',
    borderColor: '#28335F',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 6,
  },
  dashboardHostingChip: {
    backgroundColor: '#241A46',
    borderColor: '#7C5CFF',
    borderWidth: 1,
  },
  dashboardHostingChipText: {
    color: '#E5DEFF',
    fontWeight: '700',
  },
  dashboardAttentionList: {
    gap: 12,
    marginTop: 8,
  },
  dashboardAttentionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  homeActionCardWrap: {
    flexGrow: 1,
    flexBasis: isWeb ? 220 : undefined,
    maxWidth: isWeb ? 320 : undefined,
    minWidth: 100,
  },
  homeActionCard: {
    minWidth: 100,
    backgroundColor: '#14192D',
    borderRadius: 22,
    borderWidth: 1,
  },
  homeActionCardActive: {
    backgroundColor: '#18213A',
  },
  homeActionCardContent: {
    paddingVertical: 16,
  },
  homeActionValue: {
    color: '#F4F6FF',
    fontSize: 24,
    fontWeight: '800',
  },
  homeActionLabel: {
    color: '#95A0C8',
    marginTop: 4,
  },
  focusedActionPanel: {
    borderColor: '#33D1FF',
    borderWidth: 1,
  },
  panel: {
    backgroundColor: '#151A2D',
    borderRadius: 24,
    width: isWeb ? '100%' : undefined,
  },
  sectionHeader: {
    gap: 4,
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#F5F7FF',
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: '#95A0C8',
    lineHeight: 20,
  },
  listText: {
    color: '#D8DDF4',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 4,
  },
  progress: {
    marginTop: 12,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#262C44',
  },
  quickPath: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  inviteTargetGroup: {
    gap: 6,
    maxWidth: 240,
  },
  inviteBusyMeta: {
    alignItems: 'flex-start',
    gap: 6,
  },
  friendBusyChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  friendBusyText: {
    color: '#FFD8DE',
    fontWeight: '700',
  },
  friendMaybeBusyChip: {
    backgroundColor: '#3A2A12',
    borderColor: '#F0C15C',
    borderWidth: 1,
  },
  friendMaybeBusyText: {
    color: '#FFE7AE',
    fontWeight: '700',
  },
  igdbSearchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
  },
  igdbSearchStack: {
    gap: 10,
    alignItems: 'stretch',
  },
  igdbSearchInputInline: {
    flexGrow: 1,
    flexBasis: isWeb ? 620 : undefined,
    minWidth: isWeb ? 0 : 240,
    maxWidth: isWeb ? 760 : undefined,
  },
  igdbSearchInputStacked: {
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
  },
  igdbSearchButton: {
    alignSelf: 'flex-start',
  },
  igdbDismissRow: {
    alignItems: 'flex-end',
    marginTop: 6,
    marginBottom: -2,
  },
  igdbResultCard: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 12,
  },
  igdbResultRow: {
    flexDirection: 'row',
    gap: 12,
  },
  igdbResultMeta: {
    flex: 1,
    gap: 6,
  },
  igdbCoverImage: {
    backgroundColor: '#1F2744',
    borderRadius: 14,
    height: 108,
    width: 80,
  },
  igdbCoverPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#1F2744',
    borderRadius: 14,
    height: 108,
    justifyContent: 'center',
    width: 80,
  },
  igdbCoverPlaceholderText: {
    color: '#DDE4FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  friendCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  friendRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  friendRequestCard: {
    gap: 8,
    marginTop: 14,
    paddingTop: 4,
  },
  friendCodeSurface: {
    alignItems: 'center',
    backgroundColor: '#10162A',
    borderColor: '#2C3560',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  friendCodeValue: {
    color: '#F5F7FF',
    fontFamily: isWeb ? 'ui-monospace, SFMono-Regular, Menlo, monospace' : undefined,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 1.1,
    textAlign: 'center',
  },
  avatar: {
    backgroundColor: '#7C5CFF',
  },
  avatarLarge: {
    backgroundColor: '#33D1FF',
  },
  friendMeta: {
    flex: 1,
    gap: 2,
  },
  friendStatus: {
    color: '#7DFFB3',
    fontSize: 13,
    fontWeight: '700',
  },
  friendGroupsToolbar: {
    alignItems: 'flex-start',
    marginTop: -2,
  },
  friendGroupFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  friendGroupChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  friendGroupsDialog: {
    alignSelf: 'center',
    width: isWeb ? 680 : undefined,
    maxWidth: isWeb ? 680 : undefined,
  },
  compactDialog: {
    alignSelf: 'center',
    maxWidth: isWeb ? 520 : undefined,
  },
  friendGroupsInputRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  friendGroupsInput: {
    flex: 1,
    minWidth: isWeb ? 260 : undefined,
  },
  friendGroupsManagerList: {
    gap: 10,
    marginTop: 16,
  },
  friendGroupsManagerRow: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
  },
  friendGroupsManagerRowContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  friendGroupsRenameRow: {
    gap: 10,
  },
  friendGroupsRowActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  friendNote: {
    color: '#9AA5CA',
    fontSize: 13,
    lineHeight: 18,
  },
  discordGuildPickerButton: {
    alignItems: 'center',
    borderColor: '#32417E',
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  discordGuildPickerContent: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  discordGuildPickerPrefix: {
    color: '#9AA5CA',
    fontSize: 14,
  },
  discordGuildPickerValue: {
    color: '#8A6CFF',
    fontSize: 14,
    fontWeight: '700',
  },
  discordGuildSummaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  discordGuildInlineAvatar: {
    backgroundColor: '#5865F2',
    marginRight: 0,
  },
  discordGuildSummaryAvatar: {
    backgroundColor: '#5865F2',
  },
  supportingText: {
    color: '#C7CDEA',
    marginTop: 4,
    marginBottom: 2,
  },
  gameLibraryCardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  gameLibraryMeta: {
    flex: 1,
    minWidth: 0,
  },
  gameLibraryCoverImage: {
    backgroundColor: '#1F2744',
    borderRadius: 16,
    height: 120,
    width: 88,
  },
  gameLibraryCoverImageCompact: {
    height: 96,
    width: 72,
  },
  gameLibraryCoverPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#1D2543',
    borderColor: '#32417E',
    borderRadius: 16,
    borderWidth: 1,
    height: 120,
    justifyContent: 'center',
    paddingHorizontal: 10,
    width: 88,
  },
  gameLibraryCoverPlaceholderText: {
    color: '#F5F7FF',
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 1,
  },
  gameLibraryCoverPlaceholderSubtext: {
    color: '#9AA5CA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.1,
    marginTop: 4,
    textTransform: 'uppercase',
  },
  subsectionTitle: {
    color: '#F5F7FF',
    fontWeight: '700',
    marginTop: 10,
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  inputShell: {
    backgroundColor: '#171D35',
    borderColor: '#2C3560',
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
  },
  schedulerStep: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    marginTop: 14,
    padding: 14,
    width: isWeb ? '100%' : undefined,
  },
  schedulerStepHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  stepBadge: {
    backgroundColor: '#7DFFB3',
    borderRadius: 999,
    color: '#07140F',
    fontSize: 16,
    fontWeight: '900',
    height: 34,
    lineHeight: 34,
    textAlign: 'center',
    width: 34,
  },
  gamePickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  lobbyGameCarousel: {
    gap: 10,
    width: '100%',
  },
  lobbyGameCarouselHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  lobbyGameCarouselStatus: {
    color: '#95A0C8',
    fontSize: 13,
    fontWeight: '700',
  },
  lobbyGameCarouselControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  lobbyGameCarouselDesktopTrack: {
    flexDirection: 'row',
    gap: 10,
  },
  lobbyGameCarouselDesktopCard: {
    flex: 1,
    minWidth: 0,
    maxWidth: undefined,
  },
  lobbyGameCarouselMobileTrack: {
    paddingRight: 12,
  },
  lobbyGameCarouselMobileCard: {
    flexGrow: 0,
    minWidth: undefined,
    maxWidth: undefined,
  },
  lobbyGameCardMeta: {
    gap: 4,
    minWidth: 0,
  },
  lobbyGameCoverImage: {
    alignSelf: 'center',
    backgroundColor: '#1F2744',
    borderRadius: 16,
    height: 128,
    marginBottom: 4,
    width: 92,
  },
  lobbyGameCoverPlaceholder: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#1D2543',
    borderColor: '#32417E',
    borderRadius: 16,
    borderWidth: 1,
    height: 128,
    justifyContent: 'center',
    marginBottom: 4,
    paddingHorizontal: 10,
    width: 92,
  },
  lobbyGameCoverPlaceholderText: {
    color: '#F5F7FF',
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 1,
  },
  lobbyGameCoverPlaceholderSubtext: {
    color: '#9AA5CA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.1,
    marginTop: 4,
    textTransform: 'uppercase',
  },
  inlineLoadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  gamePickCard: {
    backgroundColor: '#171D35',
    borderColor: '#2C3560',
    borderRadius: 18,
    borderWidth: 1,
    flexGrow: 1,
    flexBasis: isWeb ? 240 : undefined,
    gap: 8,
    minWidth: 150,
    maxWidth: isWeb ? 280 : undefined,
    padding: 12,
  },
  gamePickCardSelected: {
    backgroundColor: '#1E3143',
    borderColor: '#7DFFB3',
  },
  gamePickTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  rouletteHero: {
    alignItems: 'center',
    backgroundColor: '#1A2040',
    borderColor: '#32417E',
    borderRadius: 36,
    borderWidth: 1,
    minHeight: 240,
    justifyContent: 'center',
    padding: 24,
    gap: 12,
    width: isWeb ? '100%' : undefined,
    maxWidth: isWeb ? 720 : undefined,
    alignSelf: isWeb ? 'center' : undefined,
  },
  rouletteStage: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    position: 'relative',
    width: '100%',
  },
  rouletteCoverImage: {
    backgroundColor: '#1F2744',
    borderRadius: 24,
    height: 188,
    width: 136,
  },
  rouletteCoverPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#1D2543',
    borderColor: '#32417E',
    borderRadius: 24,
    borderWidth: 1,
    height: 188,
    justifyContent: 'center',
    paddingHorizontal: 12,
    width: 136,
  },
  rouletteCoverPlaceholderText: {
    color: '#F5F7FF',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  rouletteCoverPlaceholderSubtext: {
    color: '#9AA5CA',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginTop: 6,
    textTransform: 'uppercase',
  },
  rouletteValue: {
    color: '#FFFFFF',
    fontWeight: '800',
    textAlign: 'center',
  },
  rouletteConfettiOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  rouletteConfettiPiece: {
    borderRadius: 999,
    height: 18,
    left: '50%',
    marginLeft: -4,
    marginTop: -9,
    position: 'absolute',
    top: '50%',
    width: 8,
  },
  rouletteScopeDialog: {
    alignSelf: 'center',
    width: isWeb ? 760 : undefined,
    maxWidth: isWeb ? 760 : undefined,
  },
  rouletteScopeDialogScrollShell: {
    borderTopColor: '#2A3150',
    borderTopWidth: 1,
    paddingHorizontal: 0,
  },
  rouletteScopeDialogScrollArea: {
    maxHeight: 420,
  },
  rouletteScopeDialogContent: {
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  rouletteScopeGameRow: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
  },
  rouletteScopeGameRowSelected: {
    backgroundColor: '#17223F',
    borderColor: '#7C5CFF',
  },
  rouletteScopeGameRowContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  rouletteScopeGameThumb: {
    backgroundColor: '#1F2744',
    borderRadius: 12,
    height: 72,
    width: 54,
  },
  rouletteScopeGameThumbPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#1D2543',
    borderColor: '#32417E',
    borderRadius: 12,
    borderWidth: 1,
    height: 72,
    justifyContent: 'center',
    width: 54,
  },
  rouletteScopeGameThumbPlaceholderText: {
    color: '#F5F7FF',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  rouletteScopeGameMeta: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  availabilityRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  availabilitySummaryCard: {
    alignItems: 'center',
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginTop: 12,
    padding: 14,
    width: isWeb ? '100%' : undefined,
  },
  availabilitySummaryValue: {
    color: '#F5F7FF',
    fontSize: 28,
    fontWeight: '800',
  },
  dayPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  dayChip: {
    backgroundColor: '#20263F',
  },
  selectedDayChip: {
    backgroundColor: '#32417E',
  },
  eventTimePanel: {
    backgroundColor: '#151B31',
    borderColor: '#2C3560',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    width: isWeb ? '100%' : undefined,
  },
  eventTimeHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  eventTimeTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  pickerFieldGroup: {
    gap: 12,
    marginTop: 4,
  },
  timeRangeButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pickerSummary: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  scheduleEventCard: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    marginTop: 12,
    padding: 14,
  },
  inviteResponseCard: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    marginTop: 12,
    padding: 14,
  },
  inviteCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  inviteDecisionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  inviteHistorySection: {
    gap: 8,
    marginTop: 8,
  },
  inviteHistoryCard: {
    backgroundColor: '#0E1427',
    borderRadius: 16,
    gap: 6,
    padding: 12,
  },
  inviteHistoryCurrentCard: {
    borderColor: '#32417E',
    borderWidth: 1,
  },
  inviteHistoryMutedCard: {
    opacity: 0.8,
  },
  inviteHistoryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  inviteGroupSection: {
    gap: 10,
    marginTop: 10,
  },
  hostMemberCard: {
    backgroundColor: '#151B31',
    borderColor: '#28335F',
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  inviteAcceptedChip: {
    backgroundColor: '#103326',
    borderColor: '#1F8F5F',
    borderWidth: 1,
  },
  inviteAcceptedText: {
    color: '#D8FFEA',
    fontWeight: '700',
  },
  inviteDeclinedChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  inviteDeclinedText: {
    color: '#FFD8DE',
    fontWeight: '700',
  },
  inviteSuggestedChip: {
    backgroundColor: '#132B4A',
    borderColor: '#33D1FF',
    borderWidth: 1,
  },
  inviteSuggestedText: {
    color: '#D9F7FF',
    fontWeight: '700',
  },
  invitePendingChip: {
    backgroundColor: '#252B49',
    borderColor: '#52619A',
    borderWidth: 1,
  },
  invitePendingText: {
    color: '#DDE4FF',
    fontWeight: '700',
  },
  inviteHistoryMutedChip: {
    backgroundColor: '#20263F',
    borderColor: '#364063',
    borderWidth: 1,
  },
  inviteHistoryMutedText: {
    color: '#ADB7DE',
    fontWeight: '700',
  },
  availabilityWindowCard: {
    backgroundColor: '#10162A',
    borderColor: '#1F8F5F',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 10,
    padding: 12,
  },
  timeBlockPanel: {
    backgroundColor: '#10162A',
    borderColor: '#2C3560',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 14,
    padding: 16,
  },
  timeBlockHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  timeBlockTitle: {
    color: '#F5F7FF',
    fontSize: 30,
    fontWeight: '900',
  },
  timeBlockGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  availabilityDay: {
    color: '#F5F7FF',
    fontWeight: '700',
    width: 36,
  },
  scheduleLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
    marginBottom: 4,
  },
  availableLegendChip: {
    backgroundColor: '#103326',
    borderColor: '#1F8F5F',
    borderWidth: 1,
  },
  availableLegendText: {
    color: '#7DFFB3',
  },
  unavailableLegendChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  unavailableLegendText: {
    color: '#FF8A98',
  },
  slotRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    flex: 1,
  },
  availableSlotChip: {
    backgroundColor: '#103326',
    borderColor: '#1F8F5F',
    borderWidth: 1,
  },
  availableSlotText: {
    color: '#D8FFEA',
    fontWeight: '700',
  },
  unavailableSlotChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  unavailableSlotText: {
    color: '#FFD8DE',
    fontWeight: '700',
  },
  availabilityWeekOverview: {
    backgroundColor: '#10162A',
    borderRadius: 18,
    gap: 8,
    marginTop: 14,
    padding: 12,
  },
  availabilityMiniRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  availabilityMiniDay: {
    color: '#F5F7FF',
    fontSize: 12,
    fontWeight: '800',
    width: 34,
  },
  availabilityMiniSlots: {
    flexDirection: 'row',
    flex: 1,
    gap: 6,
  },
  availabilityMiniOn: {
    backgroundColor: '#2BE38D',
    borderRadius: 999,
    flex: 1,
    height: 8,
  },
  availabilityMiniOff: {
    backgroundColor: '#B84A5A',
    borderRadius: 999,
    flex: 1,
    height: 8,
    opacity: 0.75,
  },
  countdownChip: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  notificationHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  notificationMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  notificationStatusChip: {
    backgroundColor: '#252B49',
  },
  lobbyAddGameDialog: {
    alignSelf: 'center',
  },
  lobbyAddGameDialogScrollShell: {
    borderTopColor: '#2A3150',
    borderTopWidth: 1,
    paddingHorizontal: 0,
  },
  lobbyAddGameDialogScrollArea: {
    maxHeight: 420,
  },
  lobbyAddGameDialogContent: {
    gap: 12,
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  divider: {
    backgroundColor: '#2A3150',
    marginVertical: 12,
  },
  profileHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileSummary: {
    gap: 6,
  },
  profileCardStretch: {
    height: '100%',
  },
  statusChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#252B49',
  },
  fab: {
    position: 'absolute',
    right: 16,
    bottom: 18,
    backgroundColor: '#7C5CFF',
  },
});
