import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  loginScreen: {
    flex: 1,
    backgroundColor: '#0B1020',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  loginCard: {
    backgroundColor: '#151A2D',
    borderColor: '#2C3560',
    borderRadius: 28,
    borderWidth: 1,
    padding: 22,
    gap: 10,
  },
  loginTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  demoChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#252B49',
    marginBottom: 4,
  },
  input: {
    backgroundColor: '#171A2A',
  },
  helperText: {
    color: '#95A0C8',
  },
  successText: {
    color: '#7DFFB3',
  },
  loginButton: {
    marginTop: 6,
  },
  screen: {
    flex: 1,
    backgroundColor: '#0B1020',
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 64,
    paddingBottom: 120,
    gap: 16,
  },
  eyebrow: {
    color: '#7DFFB3',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  pageTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  pageSubtitle: {
    color: '#A7B0D6',
    fontSize: 15,
    lineHeight: 22,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  segmented: {
    marginTop: 4,
  },
  heroCard: {
    backgroundColor: '#161B31',
    borderColor: '#2C3560',
    borderRadius: 28,
    borderWidth: 1,
    padding: 20,
    gap: 14,
  },
  liveChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#252B49',
  },
  heroTitle: {
    color: '#F7F8FF',
    fontWeight: '800',
  },
  heroCopy: {
    color: '#B9C0E0',
    fontSize: 15,
    lineHeight: 22,
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    minWidth: 100,
    flexGrow: 1,
    backgroundColor: '#14192D',
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
  },
  statValue: {
    color: '#F4F6FF',
    fontSize: 24,
    fontWeight: '800',
  },
  statLabel: {
    color: '#95A0C8',
    marginTop: 4,
  },
  panel: {
    backgroundColor: '#151A2D',
    borderRadius: 24,
  },
  sectionHeader: {
    gap: 4,
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#F5F7FF',
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: '#95A0C8',
    lineHeight: 20,
  },
  listText: {
    color: '#D8DDF4',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 4,
  },
  progress: {
    marginTop: 12,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#262C44',
  },
  quickPath: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  igdbSearchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
  },
  igdbSearchInput: {
    flexGrow: 1,
    minWidth: 240,
  },
  igdbResultCard: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 12,
  },
  igdbResultRow: {
    flexDirection: 'row',
    gap: 12,
  },
  igdbResultMeta: {
    flex: 1,
    gap: 6,
  },
  igdbCoverImage: {
    backgroundColor: '#1F2744',
    borderRadius: 14,
    height: 108,
    width: 80,
  },
  igdbCoverPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#1F2744',
    borderRadius: 14,
    height: 108,
    justifyContent: 'center',
    width: 80,
  },
  igdbCoverPlaceholderText: {
    color: '#DDE4FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  friendCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  friendRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  friendRequestCard: {
    gap: 8,
    marginTop: 14,
    paddingTop: 4,
  },
  avatar: {
    backgroundColor: '#7C5CFF',
  },
  avatarLarge: {
    backgroundColor: '#33D1FF',
  },
  friendMeta: {
    flex: 1,
    gap: 2,
  },
  friendStatus: {
    color: '#7DFFB3',
    fontSize: 13,
    fontWeight: '700',
  },
  friendNote: {
    color: '#9AA5CA',
    fontSize: 13,
    lineHeight: 18,
  },
  discordGuildPickerButton: {
    alignItems: 'center',
    borderColor: '#32417E',
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  discordGuildPickerContent: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  discordGuildPickerPrefix: {
    color: '#9AA5CA',
    fontSize: 14,
  },
  discordGuildPickerValue: {
    color: '#8A6CFF',
    fontSize: 14,
    fontWeight: '700',
  },
  discordGuildSummaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  discordGuildInlineAvatar: {
    backgroundColor: '#5865F2',
    marginRight: 0,
  },
  discordGuildSummaryAvatar: {
    backgroundColor: '#5865F2',
  },
  supportingText: {
    color: '#C7CDEA',
    marginTop: 4,
    marginBottom: 2,
  },
  subsectionTitle: {
    color: '#F5F7FF',
    fontWeight: '700',
    marginTop: 10,
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  schedulerStep: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    marginTop: 14,
    padding: 14,
  },
  schedulerStepHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  stepBadge: {
    backgroundColor: '#7DFFB3',
    borderRadius: 999,
    color: '#07140F',
    fontSize: 16,
    fontWeight: '900',
    height: 34,
    lineHeight: 34,
    textAlign: 'center',
    width: 34,
  },
  gamePickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  gamePickCard: {
    backgroundColor: '#171D35',
    borderColor: '#2C3560',
    borderRadius: 18,
    borderWidth: 1,
    flexGrow: 1,
    gap: 8,
    minWidth: 150,
    padding: 12,
  },
  gamePickCardSelected: {
    backgroundColor: '#1E3143',
    borderColor: '#7DFFB3',
  },
  gamePickTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  rouletteHero: {
    alignItems: 'center',
    backgroundColor: '#1A2040',
    borderColor: '#32417E',
    borderRadius: 160,
    borderWidth: 1,
    minHeight: 240,
    justifyContent: 'center',
    padding: 24,
    gap: 12,
  },
  rouletteValue: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  availabilityRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  availabilitySummaryCard: {
    alignItems: 'center',
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginTop: 12,
    padding: 14,
  },
  availabilitySummaryValue: {
    color: '#F5F7FF',
    fontSize: 28,
    fontWeight: '800',
  },
  dayPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  dayChip: {
    backgroundColor: '#20263F',
  },
  selectedDayChip: {
    backgroundColor: '#32417E',
  },
  eventTimePanel: {
    backgroundColor: '#151B31',
    borderColor: '#2C3560',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  eventTimeHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  eventTimeTitle: {
    color: '#F5F7FF',
    fontWeight: '800',
  },
  pickerFieldGroup: {
    gap: 12,
    marginTop: 4,
  },
  timeRangeButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pickerSummary: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  scheduleEventCard: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    marginTop: 12,
    padding: 14,
  },
  inviteResponseCard: {
    backgroundColor: '#10162A',
    borderColor: '#28335F',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    marginTop: 12,
    padding: 14,
  },
  inviteCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  inviteDecisionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  inviteHistorySection: {
    gap: 8,
    marginTop: 8,
  },
  inviteHistoryCard: {
    backgroundColor: '#0E1427',
    borderRadius: 16,
    gap: 6,
    padding: 12,
  },
  inviteHistoryCurrentCard: {
    borderColor: '#32417E',
    borderWidth: 1,
  },
  inviteHistoryMutedCard: {
    opacity: 0.8,
  },
  inviteHistoryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  inviteGroupSection: {
    gap: 10,
    marginTop: 10,
  },
  hostMemberCard: {
    backgroundColor: '#151B31',
    borderColor: '#28335F',
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  inviteAcceptedChip: {
    backgroundColor: '#103326',
    borderColor: '#1F8F5F',
    borderWidth: 1,
  },
  inviteAcceptedText: {
    color: '#D8FFEA',
    fontWeight: '700',
  },
  inviteDeclinedChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  inviteDeclinedText: {
    color: '#FFD8DE',
    fontWeight: '700',
  },
  inviteSuggestedChip: {
    backgroundColor: '#132B4A',
    borderColor: '#33D1FF',
    borderWidth: 1,
  },
  inviteSuggestedText: {
    color: '#D9F7FF',
    fontWeight: '700',
  },
  invitePendingChip: {
    backgroundColor: '#252B49',
    borderColor: '#52619A',
    borderWidth: 1,
  },
  invitePendingText: {
    color: '#DDE4FF',
    fontWeight: '700',
  },
  inviteHistoryMutedChip: {
    backgroundColor: '#20263F',
    borderColor: '#364063',
    borderWidth: 1,
  },
  inviteHistoryMutedText: {
    color: '#ADB7DE',
    fontWeight: '700',
  },
  availabilityWindowCard: {
    backgroundColor: '#10162A',
    borderColor: '#1F8F5F',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 10,
    padding: 12,
  },
  timeBlockPanel: {
    backgroundColor: '#10162A',
    borderColor: '#2C3560',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 14,
    padding: 16,
  },
  timeBlockHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  timeBlockTitle: {
    color: '#F5F7FF',
    fontSize: 30,
    fontWeight: '900',
  },
  timeBlockGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  availabilityDay: {
    color: '#F5F7FF',
    fontWeight: '700',
    width: 36,
  },
  scheduleLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
    marginBottom: 4,
  },
  availableLegendChip: {
    backgroundColor: '#103326',
    borderColor: '#1F8F5F',
    borderWidth: 1,
  },
  availableLegendText: {
    color: '#7DFFB3',
  },
  unavailableLegendChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  unavailableLegendText: {
    color: '#FF8A98',
  },
  slotRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    flex: 1,
  },
  availableSlotChip: {
    backgroundColor: '#103326',
    borderColor: '#1F8F5F',
    borderWidth: 1,
  },
  availableSlotText: {
    color: '#D8FFEA',
    fontWeight: '700',
  },
  unavailableSlotChip: {
    backgroundColor: '#35181E',
    borderColor: '#B84A5A',
    borderWidth: 1,
  },
  unavailableSlotText: {
    color: '#FFD8DE',
    fontWeight: '700',
  },
  availabilityWeekOverview: {
    backgroundColor: '#10162A',
    borderRadius: 18,
    gap: 8,
    marginTop: 14,
    padding: 12,
  },
  availabilityMiniRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  availabilityMiniDay: {
    color: '#F5F7FF',
    fontSize: 12,
    fontWeight: '800',
    width: 34,
  },
  availabilityMiniSlots: {
    flexDirection: 'row',
    flex: 1,
    gap: 6,
  },
  availabilityMiniOn: {
    backgroundColor: '#2BE38D',
    borderRadius: 999,
    flex: 1,
    height: 8,
  },
  availabilityMiniOff: {
    backgroundColor: '#B84A5A',
    borderRadius: 999,
    flex: 1,
    height: 8,
    opacity: 0.75,
  },
  countdownChip: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  notificationHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  divider: {
    backgroundColor: '#2A3150',
    marginVertical: 12,
  },
  profileHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileSummary: {
    gap: 6,
  },
  statusChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#252B49',
  },
  fab: {
    position: 'absolute',
    right: 16,
    bottom: 18,
    backgroundColor: '#7C5CFF',
  },
});
